# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FindDataset
                                 A QGIS plugin
 Finds datatesets, from a specific folder(s), that intersect a location in the map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-17
        copyright            : (C) 2018 by Luis Calisto and Andre Mano
        email                : luis.calisto@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FindDataset class from file FindDataset.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .find_dataset import FindDataset
    return FindDataset(iface)
